#!/bin/sh

# Enable 'errexit' and 'nounset'.
set -e
set -u

# Set a root password so that it's possible to log into the system once it has
# booted. The hash was created with 'mkpasswd --method=SHA-512 --rounds=500000'
# and matches this password:
#
#   i forgot to change this password and will therefore endure eternal embarrassment
#
usermod -p '$6$rounds=500000$H0wKVDcFCJ$tkoiaCOXdZSuCDQHqospThnJLGzue6bFjZG6ks3LCUuGO3Vc3lKud44QO8v65OgmT7.HtAgd2XuPZnZP5qYma0' root
