#!/bin/sh

# Enable 'errexit' and 'nounset'.
set -e
set -u

# The initrd image contains busybox (shell and utilities), an init script, some
# kernel modules (loop, squashfs and network interface drivers), and tools for
# fetching the root squashfs image. The init script will mount the squashfs
# image with a tmpfs overlay, and then switch execution to the real init inside
# the squashfs image.

# Copy kernel modules that are necessary to mount the root filesystem. These
# include loop and squashfs for the image itself, plus any additional modules
# needed to obtain the image. After that, additional modules can be loaded from
# within the newly mounted root.
#
# Loop over the modules and look up their full paths in the modules.dep file.
# Handle module and firmware dependencies. Copy the files to the target
# directory while preserving the directory structure with cpio. The modules.dep
# file was created by running depmod in 30-C-kernel.
modules_dep_path="${RIB_DIR_ROOTFS}/lib/modules/${RIB_KERNEL_VERSION}/modules.dep"
for kmod in \
	bnx2 \
	bnx2x \
	e1000 \
	e1000e \
	igb \
	ixgbe \
	loop \
	squashfs \
	tg3 \
	virtio_net \
	${RIB_KMOD_INCLUDE:-} \
; do
	# Firmware dependencies.
	modinfo -F firmware "$kmod" | while read fw_path
	do
		# Check whether firmware exists.
		if [ ! -f "$RIB_DIR_ROOTFS"/lib/firmware/"$fw_path" ]; then
			# Warn and continue.
			printf >&2 "WARNING: Module '%s' firmware dependency '%s' not found in '%s'.\n" \
				"$kmod" \
				"$fw_path" \
				"$RIB_DIR_ROOTFS"/lib/firmware/
			continue
		fi

		# Print un-anchored path relative to the rib root.
		printf "lib/firmware/%s\n" \
			"$fw_path"
	done

	# Module dependencies.
	grep -F "/${kmod}.ko:" "$modules_dep_path" | while read kmod_path deps
	do
		# Print un-anchored path relative to the rib root.
		printf "lib/modules/%s/%s\n" \
			"$RIB_KERNEL_VERSION" \
			"${kmod_path%:}"
		for dep_path in $deps
		do
			# Print un-anchored path relative to the rib root.
			printf "lib/modules/%s/%s\n" \
				"$RIB_KERNEL_VERSION" \
				"$dep_path"
		done
	done
done | sort -u | (
	cd "$RIB_DIR_ROOTFS"
	cpio -pmd "$VTEMP"
)

# Create the module dependency lists. This produces a harmless warning about
# missing files.
printf "Resolving module dependencies (ignore warnings) ...\n"
depmod -b "$VTEMP" "$RIB_KERNEL_VERSION"

# Prepare busybox static binary. This relies on the busybox static binary
# having already been downloaded and made available in the files directory.
mkdir "$VTEMP"/bin
mv "$RIB_DIR_TEMP"/busybox "$VTEMP"/bin/
chmod +x "$VTEMP"/bin/busybox

# Copy binaries with dependencies. These were prepared by earlier build
# scripts, so that everything is readily available within the cpio archive.
(
	cd "$VTEMP"
	cpio -i < "$RIB_DIR_TEMP"/init_exes.cpio
)

# Copy the simple init script from the file repository into the initrd build
# directory. The kernel tries to execute /init first, then /sbin/init and a few
# more alteratives, ref init/main.c in the kernel source.
cp "$RIB_DIR_FILES"/init "$VTEMP"/
chmod +x "$VTEMP"/init

# Create the initrd cpio archive and compress it with gzip. The gzip
# compression will not do much with the xz-compressed squashfs image, so
# there's not much to gain from compression at this stage.
(
	cd "$VTEMP"
	find . | cpio --create -H newc
) | gzip -1 > "$RIB_DIR_DIST"/initrd-"$RIB_KERNEL_VERSION".cpio.gz
