#!/bin/sh

# Enable 'errexit' and 'nounset'.
set -e
set -u

# Disable installation of recommended packages. This was enabled by default in
# upstream apt commit 113d2d69 back in 2008, and makes apt pull in a large
# number of arguably unnecessary packages; disable this in the interest of
# saving memory.
cat > /etc/apt/apt.conf.d/10norecommends << EOF
APT::Install-Recommends "false";
EOF

# Enable compressed package indexes, supported since upstream APT commit
# 01606def back in 2010. This helps to keep the memory footprint low.
cat > /etc/apt/apt.conf.d/15compress-indexes << EOF
Acquire::GzipIndexes "true";
Acquire::CompressionTypes::Order:: "gz";
EOF
