#!/bin/sh

# Enable 'errexit' and 'nounset'.
set -e
set -u

# Disable service invocations, primarily to avoid problems with package
# installs that invoke service actions, and are prone to failing when run from
# within a chroot environment, especially when fakechroot is involved.
#
# This file is removed in a later step, ref 77-C-remove_policy-rc.d. See also
# /usr/share/doc/sysv-rc/README.policy-rc.d.gz for more information.
cat > /usr/sbin/policy-rc.d << EOF
#!/bin/sh
exit 101
EOF
chmod +x /usr/sbin/policy-rc.d

# Set DEBIAN_FRONTEND and TERM, to avoid debconf warnings.
DEBIAN_FRONTEND="noninteractive"
export DEBIAN_FRONTEND
TERM="linux"
export TERM

# Upgrade packages.
apt-get \
	--quiet \
	--assume-yes \
	-o DPkg::options::="--force-confnew" \
	dist-upgrade

# Remove some relatively large packages.
#
# o wget has priority 'important' and is thus installed by default. It pulls in
#   the 20+ MB icu library, so we remove wget first, and the libicu will be
#   removed by the 'autoremove' operation later.
#
# o binutils was installed by the 'fakechroot' debootstrap variant. It
#   is not needed at this point.
apt-get --quiet --assume-yes --purge remove \
	wget \
	binutils \

# Install some generally useful packages.
apt-get \
	--quiet \
	--assume-yes \
	-o DPkg::options::="--force-confnew" \
	install \
		ethtool \
		strace \
		tcpdump \
