#!/bin/sh

# Enable 'errexit' and 'nounset'.
set -e
set -u

# Determine architecture.
arch=`dpkg --print-architecture`

# Determine package name. The '/candidate' version indicator will ensure that
# we select the desired package version set by package pin priorities. Since we
# pin the kernel image to backports, this will ensure that we download the
# appropriate deb. Check Debian- and Ubuntu-style package names.
#
# Since we pipe to awk inside the subshell, the return code will be 0 even if
# the apt-cache command fails. Since sh/dash doesn't have the 'pipefail'
# option, we rely on checking the contents of the variable instead of the
# return code.
#
# The awk program will parse the dependencies, and handles not only the
# straight-forward, single-dependency, explicit dependency case; but also the
# case where there's a dependency on a virtual package (identified by angle
# brackets), and one or more real packages that provide the virtual package.
for kpkg in linux-image-"$arch" linux-image-generic
do
	kernel_package=`apt-cache depends "$kpkg"/candidate |
		awk '
			/Depends:/ {
				pkg=$2;
				if (index(pkg, "<") == 1)
					virtual=1
				else {
					print pkg;
					exit;
				}
			}
			/^    / {
				if (virtual) {
					print $1;
					exit;
				}
			}'`
	test -n "$kernel_package" && break
done

# Return failure if no candidate package was found.
test -n "$kernel_package" || {
	printf >&2 "Unable to find package for kernel image.\n"
	exit 1
}

# Download and extract.
cd "$VTEMP"
apt-get download "$kernel_package"
dpkg-deb --extract "$kernel_package"_*.deb /

# Generate module dependency list and export the version string.
kernel_version=`ls -1rt /lib/modules | tail -n1`
depmod "$kernel_version"
printf >&3 "%s\037%s\037%s\0" setenv "RIB_KERNEL_VERSION" "$kernel_version"
